#!/bin/sh

# After install or upgrade
set -e

echo "postinst script running..."

# Create log files for nsswitch modules
touch /var/log/nsswitch_openvpn.log
chmod 644 /var/log/nsswitch_openvpn.log
touch /var/log/nsswitch_wireguard.log
chmod 644 /var/log/nsswitch_wireguard.log

exit 0

#DEBHELPER#