.TH VPN-NSSWITCH 1 "2025-05-26" "vpn-nsswitch" "User Commands"
.SH NAME
vpn-nsswitch \- A tool to manage NSSwitch configuration for VPNs
.SH SYNOPSIS
.B vpn-nsswitch
[\fIoptions\fR]
.SH DESCRIPTION
\fBvpn-nsswitch\fR is a command-line tool to configure NSSwitch settings for VPN connections, such as OpenVPN and WireGuard.
.SH OPTIONS
None currently implemented.
.SH AUTHOR
Written by Your Name.
.SH SEE ALSO
NetworkManager(8)