.TH VPN-NSSWITCH 1 "2025-05-26" "vpn-nsswitch 1.0.0" "User Commands"
.SH NAME
vpn-nsswitch \- manage NSSwitch configuration for VPNs
.SH SYNOPSIS
.B vpn-nsswitch
[\fIoptions\fR]
.SH DESCRIPTION
\fBvpn-nsswitch\fR is a command-line utility used to configure NSSwitch settings to ensure proper DNS resolution when using VPN connections.

.SH OPTIONS
This command currently takes no options.

.SH AUTHOR
Matthew Elgert
