name: Build Debian Package

on:
  push:
    tags:
      - 'v*.*.*'
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y devscripts build-essential debhelper fakeroot lintian

      - name: Use build script
        run: |
          cd tools/
          ./build.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpn-nsswitch
          path: build-artifacts/*.deb

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-artifacts/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}